In [1]:
import mdtraj as md
import os
import glob
import pandas as pd

In [2]:
output_path='/global/cfs/cdirs/m4704/100125_Nature_Com_data/single_conformation/nma'

In [3]:
ref_path='/global/cfs/cdirs/m4704/100125_Nature_Com_data/Apo_holo_data/pdbs'

In [4]:
def generate_rmsd_alphaSAXS(pdb_id,ref_path,output_path):
    rmsd=[]
    ref_t=md.load(os.path.join(ref_path,pdb_id+'.pdb'))
    ref_atom=ref_t.topology.select('name CA')
    test_t = md.load(os.path.join(output_path, pdb_id+'.pdb'))
    test_atom=test_t.topology.select('name CA')
    if len(test_atom)!=len(ref_atom):
        return pdb_id+' has the wrong length'
    ca_selection=md.rmsd(test_t,ref_t,0,test_atom,ref_atom)
    return ca_selection[0]*10

In [5]:
pdb_list=[ f[:-4] for f in os.listdir(ref_path) if f.endswith('.pdb')]

In [6]:
len(pdb_list)

80

In [7]:
result={}

In [8]:
for i in pdb_list:
    try:
        result[i]=generate_rmsd_alphaSAXS(i,ref_path,output_path)
    except:
        print(f'{i} is not in the prediction dataset')

In [9]:
result

{'2K8R-1_A': 4.274497926235199,
 '1XSA-23_A': 4.290747940540314,
 '1K2H-4_A': 6.59506618976593,
 '2D9E-12_A': 3.833523690700531,
 '1P7M-18_A': 2.273441255092621,
 '1EX6_B': 5.6531500816345215,
 '2AI6-18_A': 2.9643553495407104,
 '1MO8-14_A': 20.744996070861816,
 '2KXL-8_A': 4.462212920188904,
 '1TJD_A': 1.7837749421596527,
 '2VCD-8_A': 1.5808682143688202,
 '2F63-4_A': 2.054574489593506,
 '1ROE-10_A': 4.488076269626617,
 '1CZ2-8_A': 2.7978739142417908,
 '1PUN-7_A': 3.803841769695282,
 '1WCW_A': 2.3838433623313904,
 '1ZFS-13_B': 2.433135360479355,
 '1VHL_A': 2.6123732328414917,
 '2LKC-4_A': 8.724854588508606,
 '1ZOL_A': 3.0302557349205017,
 '1NTR-7_A': 3.999658226966858,
 '1UR6-4_A': 2.1775028109550476,
 '1TNQ-33_A': 6.5153968334198,
 '1S2O_A': 3.007400929927826,
 '1JM4-15_B': 5.122198462486267,
 '1RRO_A': 0.8389937877655029,
 '2CG6_A': 6.507254242897034,
 '1MO7-3_A': 21.899242401123047,
 '1VIY_C': 2.646643817424774,
 '1RTP_1': 0.6280387938022614,
 '1JKN-15_A': 3.087535798549652,
 '1JFJ-3_A': 13.54327917098999,
 '1LAH_E': 0.4202891141176224,
 '1LIP-2_A': 1.7823521792888641,
 '1AEL-12_A': 2.593274414539337,
 '2RCS_H': 6.588011980056763,
 '1JTB-6_A': 3.021206557750702,
 '2CG7_A': 1.4003299176692963,
 '1SKT-10_A': 2.3289062082767487,
 '1QJ8_A': 4.640268385410309,
 '2K43-1_A': 2.868780791759491,
 '2JU8-9_A': 1.8631334602832794,
 '1EQM_A': 4.000774919986725,
 '1JFK_A': 12.8934907913208,
 '2NLN-4_A': 3.4841009974479675,
 '1WD7_B': 6.2256693840026855,
 '1IJA-15_A': 4.166153073310852,
 '2L51-15_B': 3.9009806513786316,
 '1FMF-4_A': 15.11350393295288,
 '2JWW-13_A': 2.7018514275550842,
 '2L50-24_A': 3.192964792251587,
 '1TJ5_A': 0.7189907878637314,
 '1URE-8_A': 1.8706463277339935,
 '1ID8-11_A': 15.628269910812378,
 '2ECK_B': 18.934967517852783,
 '4AKE_B': 17.878893613815308,
 '1GH1-7_A': 2.2627271711826324,
 '1AJ7_H': 1.1279074102640152,
 '2RS9-13_B': 3.1111520528793335,
 '1F3Y-17_A': 5.878774523735046,
 '1EEJ_B': 2.5744396448135376,
 '2UZ5-9_A': 3.113187551498413,
 '1XSC-20_A': 2.6673853397369385,
 '2LAO_A': 4.7444188594818115,
 '1EX7_A': 1.731598675251007,
 '2K0G-9_A': 3.53780061006546,
 '1ORM-9_A': 6.267277002334595,
 '2OZW-3_A': 3.832838237285614,
 '1O03_A': 0.955561101436615,
 '2KID-4_A': 2.036258578300476,
 '1W4U-9_A': 2.413296401500702,
 '1XYD-15_B': 2.161153107881546,
 '1SYM-2_B': 6.539328694343567,
 '1WUM_A': 1.8628084659576416,
 '2JU3-3_A': 2.92760968208313,
 '1LMZ-9_A': 3.389076292514801,
 '2LKD-18_A': 5.908632278442383,
 '2CJO-5_A': 1.5061208605766296,
 '1MUT-11_A': 3.6559009552001953,
 '1KRX-4_A': 3.0243322253227234}

In [10]:
df = pd.DataFrame(result.items(), columns=['Key', 'Value'])

In [11]:
df.describe()

           Value
count  80.000000
mean    4.702575
std     4.567831
min     0.420289
25%     2.270763
50%     3.099344
75%     4.838864
max    21.899242

In [12]:
pair_csv=pd.read_csv('/global/cfs/cdirs/m4704/100125_Nature_Com_data/Apo_holo_data/Table_rmsd_Apo_vs_Holo.csv',sep=';')

In [13]:
pair_dict={}
for index, i in pair_csv.iterrows():
    pair_dict[i['Apo_ID']]=i['Holo_ID']
    #pair_dict[i['Holo_ID']]=i['Apo_ID']

In [14]:
result_csv=pd.DataFrame.from_dict(result,orient='index').reset_index().rename(columns={'index':'ID',0:'RMSD'})

In [15]:
result_csv['pair_ID']=result_csv['ID'].map(pair_dict)

In [16]:
result_pair=result_csv.dropna().merge(result_csv[['ID',
'RMSD']],left_on='pair_ID',right_on='ID',suffixes=['','_pair']).drop(columns={'pair_ID'})

In [17]:
result_pair

           ID       RMSD    ID_pair  RMSD_pair
0   1XSA-23_A   4.290748  1XSC-20_A   2.667385
1    1K2H-4_A   6.595066  1ZFS-13_B   2.433135
2   2D9E-12_A   3.833524  2RS9-13_B   3.111152
3      1EX6_B   5.653150     1EX7_A   1.731599
4   2AI6-18_A   2.964355   2OZW-3_A   3.832838
5    2KXL-8_A   4.462213   2K0G-9_A   3.537801
6      1TJD_A   1.783775     1EEJ_B   2.574440
7    2F63-4_A   2.054574     1EQM_A   4.000775
8    2LKC-4_A   8.724855  2LKD-18_A   5.908632
9      1ZOL_A   3.030256     1O03_A   0.955561
10   1NTR-7_A   3.999658   1KRX-4_A   3.024332
11     1S2O_A   3.007401     1TJ5_A   0.718991
12  1JM4-15_B   5.122198     1WUM_A   1.862808
13   1MO7-3_A  21.899242  1MO8-14_A  20.744996
14     1VIY_C   2.646644     1VHL_A   2.612373
15   1JFJ-3_A  13.543279     1JFK_A  12.893491
16   1LIP-2_A   1.782352   1JTB-6_A   3.021207
17  1AEL-12_A   2.593274   1URE-8_A   1.870646
18     2RCS_H   6.588012     1AJ7_H   1.127907
19     2CG7_A   1.400330     2CG6_A   6.507254
20  1SKT-10_A   2.328906  1TNQ-33_A   6.515397
21   2K43-1_A   2.868781   2K8R-1_A   4.274498
22   2NLN-4_A   3.484101     1RRO_A   0.838994
23     1WD7_B   6.225669     1WCW_A   2.383843
24  1IJA-15_A   4.166153   2KID-4_A   2.036259
25   1FMF-4_A  15.113504  1ID8-11_A  15.628270
26  2JWW-13_A   2.701851     1RTP_1   0.628039
27  2L50-24_A   3.192965  2L51-15_B   3.900981
28     4AKE_B  17.878894     2ECK_B  18.934968
29   1GH1-7_A   2.262727   1CZ2-8_A   2.797874
30  1F3Y-17_A   5.878775  1JKN-15_A   3.087536
31   2UZ5-9_A   3.113188   2VCD-8_A   1.580868
32     2LAO_A   4.744419     1LAH_E   0.420289
33   1ORM-9_A   6.267277     1QJ8_A   4.640268
34   1W4U-9_A   2.413296   1UR6-4_A   2.177503
35   1SYM-2_B   6.539329  1XYD-15_B   2.161153
36   2JU3-3_A   2.927610   2JU8-9_A   1.863133
37   1LMZ-9_A   3.389076  1P7M-18_A   2.273441
38   2CJO-5_A   1.506121  1ROE-10_A   4.488076
39  1MUT-11_A   3.655901   1PUN-7_A   3.803842

In [19]:
AlphaFold_df=pd.read_csv('AlphaFold_RMSD.csv',index_col='ID')
AlphaFold_df=AlphaFold_df.drop(AlphaFold_df.columns[0], axis=1)

In [20]:
AlphaFold_df['RMSD_Fold'] = pd.to_numeric(AlphaFold_df['RMSD_Fold'], errors='coerce')

In [21]:
AlphaFold_df=AlphaFold_df.dropna()

In [22]:
AlphaFold_dict=AlphaFold_df.to_dict()['RMSD_Fold']

In [23]:
result_pair.dtypes

ID            object
RMSD         float64
ID_pair       object
RMSD_pair    float64
dtype: object

In [24]:
AlphaFold_df.dtypes

RMSD_Fold    float64
dtype: object

In [25]:
for index, i in result_pair.iterrows():
    result_pair.loc[index,'RMSD']-=AlphaFold_dict[i['ID']]
    result_pair.loc[index,'RMSD_pair']-=AlphaFold_dict[i['ID_pair']]

In [27]:
result_pair['RMSD_sum']=result_pair['RMSD']+result_pair['RMSD_pair']

In [28]:
result_pair.sort_values('RMSD_sum')

           ID      RMSD    ID_pair  RMSD_pair  RMSD_sum
28     4AKE_B -3.357762     2ECK_B  -3.759513 -7.117275
25   1FMF-4_A -1.511834  1ID8-11_A  -1.478940 -2.990774
6      1TJD_A -0.712956     1EEJ_B  -0.441966 -1.154923
27  2L50-24_A -0.429687  2L51-15_B  -0.681335 -1.111022
10   1NTR-7_A -0.378808   1KRX-4_A  -0.487784 -0.866592
15   1JFJ-3_A -0.071992     1JFK_A  -0.402335 -0.474327
16   1LIP-2_A -0.495849   1JTB-6_A   0.065737 -0.430112
18     2RCS_H  1.211920     1AJ7_H  -1.491750 -0.279830
39  1MUT-11_A -0.051301   1PUN-7_A  -0.226884 -0.278185
22   2NLN-4_A -0.414035     1RRO_A   0.223240 -0.190795
29   1GH1-7_A -0.270299   1CZ2-8_A   0.102049 -0.168250
14     1VIY_C -0.149134     1VHL_A   0.060158 -0.088976
36   2JU3-3_A -0.130023   2JU8-9_A   0.043151 -0.086872
2   2D9E-12_A -0.061502  2RS9-13_B  -0.007352 -0.068854
37   1LMZ-9_A -0.013715  1P7M-18_A   0.009654 -0.004061
0   1XSA-23_A  0.377315  1XSC-20_A  -0.380714 -0.003399
11     1S2O_A -0.112328     1TJ5_A   0.136114  0.023786
31   2UZ5-9_A -0.041580   2VCD-8_A   0.076918  0.035338
32     2LAO_A  0.077595     1LAH_E  -0.007499  0.070096
38   2CJO-5_A  0.026374  1ROE-10_A   0.051154  0.077528
12  1JM4-15_B  2.176387     1WUM_A  -2.082317  0.094070
34   1W4U-9_A  0.132147   1UR6-4_A   0.004065  0.136213
9      1ZOL_A  0.168355     1O03_A  -0.031728  0.136627
7    2F63-4_A  0.107709     1EQM_A   0.034128  0.141838
26  2JWW-13_A  0.044969     1RTP_1   0.165603  0.210572
21   2K43-1_A  0.000972   2K8R-1_A   0.263070  0.264042
1    1K2H-4_A  0.009438  1ZFS-13_B   0.309945  0.319383
24  1IJA-15_A  0.822979   2KID-4_A  -0.350575  0.472404
17  1AEL-12_A  0.107746   1URE-8_A   0.371918  0.479664
35   1SYM-2_B  0.239874  1XYD-15_B   0.267082  0.506955
20  1SKT-10_A -2.724002  1TNQ-33_A   3.321479  0.597477
5    2KXL-8_A  0.236057   2K0G-9_A   0.469992  0.706050
19     2CG7_A  0.474843     2CG6_A   0.314505  0.789347
4   2AI6-18_A  0.495220   2OZW-3_A   0.649469  1.144689
8    2LKC-4_A  0.652920  2LKD-18_A   0.745633  1.398553
23     1WD7_B  1.107016     1WCW_A   0.615900  1.722916
13   1MO7-3_A  1.072619  1MO8-14_A   1.075573  2.148192
3      1EX6_B  4.352210     1EX7_A  -1.656571  2.695638
30  1F3Y-17_A  2.519273  1JKN-15_A   0.381965  2.901238
33   1ORM-9_A  0.611532     1QJ8_A   3.358392  3.969924