In [1]:
import mdtraj as md
import os
import glob
import pandas as pd

In [2]:
output_path='/global/cfs/cdirs/m4704/100125_Nature_Com_data/single_conformation/nmr'

In [3]:
ref_path='/global/cfs/cdirs/m4704/100125_Nature_Com_data/Apo_holo_data/pdbs'

In [4]:
def generate_rmsd_alphaSAXS(pdb_id,ref_path,output_path):
    rmsd=[]
    ref_t=md.load(os.path.join(ref_path,pdb_id+'.pdb'))
    ref_atom=ref_t.topology.select('name CA')
    test_t = md.load(os.path.join(output_path, pdb_id+'.pdb'))
    test_atom=test_t.topology.select('name CA')
    if len(test_atom)!=len(ref_atom):
        return pdb_id+' has the wrong length'
    ca_selection=md.rmsd(test_t,ref_t,0,test_atom,ref_atom)
    return ca_selection[0]*10

In [5]:
pdb_list=[ f[:-4] for f in os.listdir(ref_path) if f.endswith('.pdb')]

In [6]:
len(pdb_list)

80

In [7]:
result={}

In [8]:
for i in pdb_list:
    try:
        result[i]=generate_rmsd_alphaSAXS(i,ref_path,output_path)
    except:
        print(f'{i} is not in the prediction dataset')

In [9]:
result

{'2K8R-1_A': 3.7439680099487305,
 '1XSA-23_A': 4.088649153709412,
 '1K2H-4_A': 6.395006775856018,
 '2D9E-12_A': 3.590703010559082,
 '1P7M-18_A': 2.488432079553604,
 '1EX6_B': 3.0724433064460754,
 '2AI6-18_A': 2.787221372127533,
 '1MO8-14_A': 18.085795640945435,
 '2KXL-8_A': 3.8860225677490234,
 '1TJD_A': 1.699306070804596,
 '2VCD-8_A': 1.5791341662406921,
 '2F63-4_A': 2.2038356959819794,
 '1ROE-10_A': 4.396737217903137,
 '1CZ2-8_A': 2.4383819103240967,
 '1PUN-7_A': 3.8825681805610657,
 '1WCW_A': 1.5908023715019226,
 '1ZFS-13_B': 2.730790376663208,
 '1VHL_A': 2.1964825689792633,
 '2LKC-4_A': 7.930576801300049,
 '1ZOL_A': 2.4884289503097534,
 '1NTR-7_A': 4.7535717487335205,
 '1UR6-4_A': 2.3095758259296417,
 '1TNQ-33_A': 5.227321982383728,
 '1S2O_A': 2.2988244891166687,
 '1JM4-15_B': 4.142813682556152,
 '1RRO_A': 1.1153163015842438,
 '2CG6_A': 7.207493782043457,
 '1MO7-3_A': 18.58777642250061,
 '1VIY_C': 2.35550194978714,
 '1RTP_1': 1.0937371850013733,
 '1JKN-15_A': 3.819941282272339,
 '1JFJ-3_A': 7.452875971794128,
 '1LAH_E': 1.4369890093803406,
 '1LIP-2_A': 1.8275569379329681,
 '1AEL-12_A': 2.695547938346863,
 '2RCS_H': 4.188855588436127,
 '1JTB-6_A': 2.7217254042625427,
 '2CG7_A': 2.424400895833969,
 '1SKT-10_A': 3.980453908443451,
 '1QJ8_A': 2.7977174520492554,
 '2K43-1_A': 2.7308693528175354,
 '2JU8-9_A': 1.880854070186615,
 '1EQM_A': 3.364425003528595,
 '1JFK_A': 11.185952425003052,
 '2NLN-4_A': 3.7740206718444824,
 '1WD7_B': 4.692208766937256,
 '1IJA-15_A': 4.365927278995514,
 '2L51-15_B': 4.283100962638855,
 '1FMF-4_A': 15.722757577896118,
 '2JWW-13_A': 2.6936575770378113,
 '2L50-24_A': 4.13036972284317,
 '1TJ5_A': 1.7409755289554596,
 '1URE-8_A': 1.6104941070079803,
 '1ID8-11_A': 16.53868317604065,
 '2ECK_B': 18.356680870056152,
 '4AKE_B': 18.923017978668213,
 '1GH1-7_A': 2.296116054058075,
 '1AJ7_H': 5.110107660293579,
 '2RS9-13_B': 3.3325934410095215,
 '1F3Y-17_A': 5.649862289428711,
 '1EEJ_B': 2.0470885932445526,
 '2UZ5-9_A': 3.0817824602127075,
 '1XSC-20_A': 2.4490326642990112,
 '2LAO_A': 4.117751121520996,
 '1EX7_A': 2.09555447101593,
 '2K0G-9_A': 3.4280717372894287,
 '1ORM-9_A': 5.581598281860352,
 '2OZW-3_A': 3.6293751001358032,
 '1O03_A': 2.4011632800102234,
 '2KID-4_A': 1.9722668826580048,
 '1W4U-9_A': 2.2773510217666626,
 '1XYD-15_B': 2.345108240842819,
 '1SYM-2_B': 5.599597096443176,
 '1WUM_A': 5.600694417953491,
 '2JU3-3_A': 2.9791006445884705,
 '1LMZ-9_A': 2.8495430946350098,
 '2LKD-18_A': 5.965339541435242,
 '2CJO-5_A': 1.4472322165966034,
 '1MUT-11_A': 3.9553987979888916,
 '1KRX-4_A': 3.4171605110168457}

In [10]:
df = pd.DataFrame(result.items(), columns=['Key', 'Value'])

In [11]:
df.describe()

           Value
count  80.000000
mean    4.541702
std     4.146548
min     1.093737
25%     2.336225
50%     3.348509
75%     4.470605
max    18.923018

In [11]:
pair_csv=pd.read_csv('/global/cfs/cdirs/m4704/100125_Nature_Com_data/Apo_holo_data/Table_rmsd_Apo_vs_Holo.csv',sep=';')

In [12]:
pair_dict={}
for index, i in pair_csv.iterrows():
    pair_dict[i['Apo_ID']]=i['Holo_ID']
    #pair_dict[i['Holo_ID']]=i['Apo_ID']

In [13]:
result_csv=pd.DataFrame.from_dict(result,orient='index').reset_index().rename(columns={'index':'ID',0:'RMSD'})

In [14]:
result_csv['pair_ID']=result_csv['ID'].map(pair_dict)

In [15]:
result_pair=result_csv.dropna().merge(result_csv[['ID',
'RMSD']],left_on='pair_ID',right_on='ID',suffixes=['','_pair']).drop(columns={'pair_ID'})

In [16]:
result_pair

           ID       RMSD    ID_pair  RMSD_pair
0   1XSA-23_A   4.088649  1XSC-20_A   2.449033
1    1K2H-4_A   6.395007  1ZFS-13_B   2.730790
2   2D9E-12_A   3.590703  2RS9-13_B   3.332593
3      1EX6_B   3.072443     1EX7_A   2.095554
4   2AI6-18_A   2.787221   2OZW-3_A   3.629375
5    2KXL-8_A   3.886023   2K0G-9_A   3.428072
6      1TJD_A   1.699306     1EEJ_B   2.047089
7    2F63-4_A   2.203836     1EQM_A   3.364425
8    2LKC-4_A   7.930577  2LKD-18_A   5.965340
9      1ZOL_A   2.488429     1O03_A   2.401163
10   1NTR-7_A   4.753572   1KRX-4_A   3.417161
11     1S2O_A   2.298824     1TJ5_A   1.740976
12  1JM4-15_B   4.142814     1WUM_A   5.600694
13   1MO7-3_A  18.587776  1MO8-14_A  18.085796
14     1VIY_C   2.355502     1VHL_A   2.196483
15   1JFJ-3_A   7.452876     1JFK_A  11.185952
16   1LIP-2_A   1.827557   1JTB-6_A   2.721725
17  1AEL-12_A   2.695548   1URE-8_A   1.610494
18     2RCS_H   4.188856     1AJ7_H   5.110108
19     2CG7_A   2.424401     2CG6_A   7.207494
20  1SKT-10_A   3.980454  1TNQ-33_A   5.227322
21   2K43-1_A   2.730869   2K8R-1_A   3.743968
22   2NLN-4_A   3.774021     1RRO_A   1.115316
23     1WD7_B   4.692209     1WCW_A   1.590802
24  1IJA-15_A   4.365927   2KID-4_A   1.972267
25   1FMF-4_A  15.722758  1ID8-11_A  16.538683
26  2JWW-13_A   2.693658     1RTP_1   1.093737
27  2L50-24_A   4.130370  2L51-15_B   4.283101
28     4AKE_B  18.923018     2ECK_B  18.356681
29   1GH1-7_A   2.296116   1CZ2-8_A   2.438382
30  1F3Y-17_A   5.649862  1JKN-15_A   3.819941
31   2UZ5-9_A   3.081782   2VCD-8_A   1.579134
32     2LAO_A   4.117751     1LAH_E   1.436989
33   1ORM-9_A   5.581598     1QJ8_A   2.797717
34   1W4U-9_A   2.277351   1UR6-4_A   2.309576
35   1SYM-2_B   5.599597  1XYD-15_B   2.345108
36   2JU3-3_A   2.979101   2JU8-9_A   1.880854
37   1LMZ-9_A   2.849543  1P7M-18_A   2.488432
38   2CJO-5_A   1.447232  1ROE-10_A   4.396737
39  1MUT-11_A   3.955399   1PUN-7_A   3.882568

In [19]:
AlphaFold_df=pd.read_csv('AlphaFold_RMSD.csv',index_col='ID')
AlphaFold_df=AlphaFold_df.drop(AlphaFold_df.columns[0], axis=1)

In [20]:
AlphaFold_df['RMSD_Fold'] = pd.to_numeric(AlphaFold_df['RMSD_Fold'], errors='coerce')

In [21]:
AlphaFold_df=AlphaFold_df.dropna()

In [22]:
AlphaFold_dict=AlphaFold_df.to_dict()['RMSD_Fold']

In [23]:
result_pair.dtypes

ID            object
RMSD         float64
ID_pair       object
RMSD_pair    float64
dtype: object

In [24]:
AlphaFold_df.dtypes

RMSD_Fold    float64
dtype: object

In [25]:
for index, i in result_pair.iterrows():
    result_pair.loc[index,'RMSD']-=AlphaFold_dict[i['ID']]
    result_pair.loc[index,'RMSD_pair']-=AlphaFold_dict[i['ID_pair']]

In [28]:
result_pair['RMSD_sum']=result_pair['RMSD']+result_pair['RMSD_pair']

In [32]:
result_pair.sort_values('RMSD_sum')

           ID      RMSD    ID_pair  RMSD_pair  RMSD_sum
15   1JFJ-3_A -6.162395     1JFK_A  -2.109873 -8.272268
28     4AKE_B -2.313638     2ECK_B  -4.337800 -6.651437
13   1MO7-3_A -2.238847  1MO8-14_A  -1.583627 -3.822474
6      1TJD_A -0.797425     1EEJ_B  -0.969317 -1.766742
25   1FMF-4_A -0.902580  1ID8-11_A  -0.568527 -1.471107
14     1VIY_C -0.440276     1VHL_A  -0.355732 -0.796008
16   1LIP-2_A -0.450644   1JTB-6_A  -0.233744 -0.684389
23     1WD7_B -0.426444     1WCW_A  -0.177141 -0.603586
29   1GH1-7_A -0.236910   1CZ2-8_A  -0.257443 -0.494353
0   1XSA-23_A  0.175216  1XSC-20_A  -0.599066 -0.423850
21   2K43-1_A -0.136939   2K8R-1_A  -0.267460 -0.404399
7    2F63-4_A  0.256971     1EQM_A  -0.602221 -0.345251
37   1LMZ-9_A -0.553248  1P7M-18_A   0.224645 -0.328604
35   1SYM-2_B -0.699858  1XYD-15_B   0.451037 -0.248821
2   2D9E-12_A -0.304322  2RS9-13_B   0.214089 -0.090233
38   2CJO-5_A -0.032515  1ROE-10_A  -0.040185 -0.072700
36   2JU3-3_A -0.078532   2JU8-9_A   0.060872 -0.017660
31   2UZ5-9_A -0.072986   2VCD-8_A   0.075184  0.002199
5    2KXL-8_A -0.340133   2K0G-9_A   0.360263  0.020130
39  1MUT-11_A  0.248197   1PUN-7_A  -0.148158  0.100039
34   1W4U-9_A -0.003798   1UR6-4_A   0.136138  0.132340
27  2L50-24_A  0.507718  2L51-15_B  -0.299215  0.208503
10   1NTR-7_A  0.375105   1KRX-4_A  -0.094956  0.280150
17  1AEL-12_A  0.210019   1URE-8_A   0.111766  0.321785
11     1S2O_A -0.820904     1TJ5_A   1.158098  0.337194
22   2NLN-4_A -0.124115     1RRO_A   0.499563  0.375447
1    1K2H-4_A -0.190622  1ZFS-13_B   0.607600  0.416978
32     2LAO_A -0.549072     1LAH_E   1.009201  0.460128
3      1EX6_B  1.771503     1EX7_A  -1.292616  0.478887
24  1IJA-15_A  1.022753   2KID-4_A  -0.414566  0.608187
8    2LKC-4_A -0.141358  2LKD-18_A   0.802341  0.660983
26  2JWW-13_A  0.036775     1RTP_1   0.631301  0.668076
4   2AI6-18_A  0.318086   2OZW-3_A   0.446006  0.764092
20  1SKT-10_A -1.072455  1TNQ-33_A   2.033404  0.960949
9      1ZOL_A -0.373472     1O03_A   1.413874  1.040402
18     2RCS_H -1.187237     1AJ7_H   2.490451  1.303214
33   1ORM-9_A -0.074147     1QJ8_A   1.515841  1.441694
19     2CG7_A  1.498914     2CG6_A   1.014744  2.513658
12  1JM4-15_B  1.197003     1WUM_A   1.655569  2.852571
30  1F3Y-17_A  2.290361  1JKN-15_A   1.114371  3.404731